SELECT A.SLRCAL_YMD AS "기준영업일" ,  B.SLRCAL_YMD AS "이전영업일"  ,  B.HLDY_SECD AS "영업코드"  ,  C.SLRCAL_YMD AS "다음영업일" , C.HLDY_SECD AS "영업코드" 
FROM YMD A , YMD B , YMD C
WHERE A.BFR_BIZN_YMD  = B.SLRCAL_YMD(+)
AND A.NEXT_BIZN_YMD = C.SLRCAL_YMD(+)
AND B.HLDY_SECD != '1'
AND A.SLRCAL_YMD >= B.SLRCAL_YMD 
OR C.HLDY_SECD != '1'
AND A.SLRCAL_YMD <= C.SLRCAL_YMD ;
/* 위에처럼 하고 싶었는데 outer join시 (+) 연산자를 사용할때에는 OR를 사용할 수 없다고한다*/

/***그래서 ANSI구문을 사용함***/
SELECT A.SLRCAL_YMD , A.HLDY_SECD ,  B.SLRCAL_YMD , B.HLDY_SECD ,  C.BFR_BIZN_YMD , C.HLDY_SECD
FROM YMD A 
LEFT OUTER JOIN YMD B 
ON A.BFR_BIZN_YMD  = B.SLRCAL_YMD 
LEFT OUTER JOIN YMD C 
ON A.NEXT_BIZN_YMD = C.SLRCAL_YMD 
WHERE B.HLDY_SECD != '1'
AND A.SLRCAL_YMD >= B.SLRCAL_YMD 
OR C.HLDY_SECD != '1'
AND A.SLRCAL_YMD <= C.SLRCAL_YMD 